remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Alex Zheng
description: Hi! Welcome to my portfolio site!

show_downloads: False

# Navigation links
nav:
  - title: Home
    url: /
  - title: CV
    url: /cv/
  - title: Data Science Portfolio
    url: /projects/
